- lib/utils/ui/scrollable_if_too_high.dart
- lib/views/pages/create_account_page.dart
Fixes #51. 
More than rendering the view scrollable, I also added some minimum spacing between the widgets. 
Note that I needed to create some `ScrollableIfTooHigh` widget, to handle widgets with a flexible size (this is the case for my spacer). This was strongly inspired from [the documentation](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html).
The things I am least sure about and that might be interesting for you to consider:
- `ScrollableIfTooHigh` is in `utils/ui`. This makes sense in my opinion, since this is also where `CircularValue` is; but I am not completely sure.
- I tend to always use `Flexible` followed by `SizedBox` in order to have a minimum spacing between widgets, which is increased in a flexible way. I did not find something that would …
> Fix create account UI overflow

- test/component/new_post_test.dart
This PR aims to fix the imports in `test/component/new_post_test.dart` that were made obselete when merging the PR "Add repositories for user and post" (due to the refactoring that happened in it).
> fix(test): use the right imports in new_post_test

- test/models/database/post/mock_post_data.dart
- test/models/database/user/mock_user_data.dart
- test/services/database/mock_post_data.dart
- test/services/database/mock_post_repository_service.dart
- test/services/database/mock_user_repository_service.dart
- test/services/database/post_repository_test.dart
Hello,
This pull request aims to provide the boiler plate code needed to mock the methods of the repositories.
This code is contained in the classes `MockPostRepositoryService` and `MockUserRepositoryService`.
Here is an example of how such a class can be used in a test to mock a repository method
```dart
late MockPostRepositoryService postRepository;
setUp(() {
// Initialize the mock
postRepository = MockPostRepositoryService();
});
test("some test", () {
final point = ...
final kmPostRadius = ...
// To mock the [getNearPosts] method when it is called with particular parameters
when(postRepository.getNearPosts(point, kmPostRadius)).thenAnswer(
// Here, it is mocked to return an empty list
(_) async => [], 
);
// From this point on, when the "postRepository.getNearPosts(point, …
```
> Mock repositories

- lib/viewmodels/login_view_model.dart
Fixes #83.
As I mentioned in #43, multiple PRs of this sprint require a UID provider. It is implemented in this PR.
> feat(uidProvider): Add a uid provider

- lib/utils/ui/circular_value.dart
- lib/views/home_content/feed/post_feed.dart
Hello,
This PR aims to fix the CircularValue widget that was wrapping it's `CircularProgressIndicator` leading to some crashes when the `CircularValue` was not integrated in a compatible parent widget.
Because of this fix, the overview is also modified to keep the `CircularProgressIndicator` centered.
This refactoring also allowed for the possibility of displaying an error message in the case where there was an error fetching the nearby posts.
Thus with this PR, if the nearby posts failed to be fetched, the error message `An error occurred` will be displayed in the overview together with a button that allows the user to refresh (retry to fetch the nearby posts).
> Fix circular value + Error message in overview

- .github/workflows/release.yaml
Just a small PR to make the release action have the correct permissions work.
Currently the action fails with 403 errors.
gh release needs this write permission. See Permissions in https://github.com/softprops/action-gh-release.
I have not found a way of testing this github action and plan on merging changes into main until it works. I know that @gruvw tested his pr #80 on a fork of the repo, but that still did not show the problem. Act is not useful either because this action needs access to a github repo and releases. If you have other ideas to test the workflow first I would be happy to know, otherwise we will just merge changes until it works.
> Add content permissions to release action

- lib/views/navigation/bottom_navigation_bar/navigation_bar_routes.dart
This PR fixes #110, by replacing "Your Challenges" by "Challenges" to avoid an overflow or having to crop the text
> fix: "Challenges" instead of "Your Challenges" to avoid overflow

- lib/views/pages/profile/posts_info/info_card_badge.dart
- lib/views/pages/profile/posts_info/info_card_comment.dart
- lib/views/pages/profile/posts_info/info_card_post.dart
- test/component/profile_page_test.dart
This PR rename key string on the badge, post and comment card. 
These widget used the same key string, which cause a test on the profile passing when the test shouldn't.
> Fix duplicate key string in profile testing

- lib/views/pages/profile/posts_info/info_card_comment.dart
- lib/views/pages/profile/posts_info/info_card_post.dart
- lib/views/pages/profile/posts_info/popup/comment_popup.dart
- lib/views/pages/profile/posts_info/popup/post_popup.dart
- test/component/profile_page_test.dart
This PR adds a pop-up to posts and comments on the user profile page.
Pop-ups allow the user to see the entire content of the post / comment.
It also adds an ink response upon clicking.
The new pop-up widgets are also entirely tested.
This widget is also working on small phone.
<image src="https://github.com/ProximaEPFL/proxima/assets/53620532/5de5990d-670f-4640-b116-488e55f07c02"
width="300"><image src="https://github.com/ProximaEPFL/proxima/assets/53620532/35e7931a-bdbe-4dd6-8c8d-dc0649c0ca91" width="301">
> Profile post and comment popup in user profile page

- test/services/database/mock_post_repository_service.dart
- test/services/database/mock_user_repository_service.dart
When writing other tests, I found that the arguments for the methods of the mocks needed to be nullable in order to use matchers like any or captureAny. You can find more information [here](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md#manually-override-a-method-with-a-non-nullable-parameter-type).
This short PR fixes this problem for the current mocks defined in the code. Please tell me if you found something I missed.
> Make user and post mock arguments nullable

- lib/main.dart
- lib/models/database/post/post_location_firestore.dart
- lib/services/database/post_repository_service.dart
- pubspec.yaml
- test/models/database/post/mock_post_data.dart
- test/services/database/post_repository_test.dart
Hello,
This PR aims to provide a proper fix to #78.
Indeed, a first fix was proposed in PR #116. 
But this implied that the overview was displaying a stream that was auto updated in real time.
After further discussions with the team, we determined that this wouldn't contribute to the user experience.
For instance, if the user is reading a post and that another is added near him, his scroll position might be offseted which can be anoying.
Thus, we chose to stay with a manual refresh for now.
In order to have a manual refresh, we need to be able to expose a `Future<List<PostFirestore>>` in `PostRepository` as previously while correcting the bug.
Technically speaking, this requires the underlying library to provide a `Future` implementation of geo queries. This feature is currently not …
> Geoflutterfireplus refactor

- lib/models/database/user/user_data.dart
- lib/models/ui/profile_data.dart
- lib/services/database/user_repository_service.dart
- lib/viewmodels/create_accout_view_model.dart
- lib/viewmodels/profile_view_model.dart
- lib/views/pages/profile/profile_page.dart
- lib/views/pages/profile/user_info/user_account.dart
- test/component/profile_page_test.dart
- test/models/database/user/mock_user_data.dart
- test/services/database/mock_user_repository_service.dart
- test/services/database/user_repository_test.dart
- test/services/test_data/firestore_user_mock.dart
This pull request implements a new user data viewmodel that provides more information for the different screens of the app. Here are the main features brought with this PR:
1. **Real username and displayname displayed** : Those two attributes of the user are now retrieved from firestore and are thus not mock data anymore. 
2. **First implementation of the centauri points** : User have now a "centauri points" field in the database. User have 0 points by default. For now, you can increment your points (+5) by clicking on the "settings" button in the user profile screen. The data you see and increment on the screen  is retrieved and stored in the database (not a mock example).
3. **centauri points test** : A new test checks that the "increment" feature of the centauri points is working …
> Username and Centauri points display 

- lib/services/database/post_repository_service.dart
- test/models/database/post/mock_post_data.dart
- test/services/database/post_repository_test.dart
- test/services/test_data/user_posts_fake_data.dart
A new query functionality on the model aspect that allows any viewmodel to retrieve the lists of posts of a given user.
This functionality will prove itself particularly useful for the viewmodel of the profile page, where we want to display all the posts of a given user.
Fixes #104
> User posts query

- lib/utils/ui/circular_value.dart
- lib/utils/ui/error_alert.dart
- lib/viewmodels/new_post_view_model.dart
- lib/views/home_content/feed/post_feed.dart
- test/component/utils/ui/circular_value_test.dart
Addresses #107 
This PR adds error handling to CircularValue. This allows us to reuse this component anywhere we have an AsyncValue, and automatically handle errors.
When the AsyncValue becomes and error, a fallback widget is built in place of the CircularValue, and an error popup is shown with a string representation of the error. The default fallback widget is an empty widget. The default fallback is empty because the circular value might be used in small spaces, where there is no room to show any text.
PostFeed has been adapted to use CircularValue, and to show the previous error message with a refresh button as a fallback widget.
NewPostViewModel has been updated with a guard, to catch errors and store them in the AsyncValue state.
You can see the error handling in action by disabling …
> Circular value error handling

- lib/services/database/challenge_repository_service.dart
- lib/views/home_content/challenge/challenge_list.dart
Fixes #216.
This fixes a crash from the challenge when there is no available challenge. It crashes [here](https://github.com/firebase/flutterfire/blob/953bf929bf19e7bbb3564c69901f5a4fca5fc981/packages/cloud_firestore/cloud_firestore/lib/src/query.dart#L734) in the real firestore. This cannot be tested with our mock firestore, since [this behaviour is not emulated in it](https://github.com/atn832/fake_cloud_firestore/blob/46fd92164bbc543534c3fdd7fe390c535bbd2847/lib/src/mock_query.dart#L230). In fact, we already had a test that checked the case where there is no challenge in-range, `challenge_repository_test.dart`:"Challenge range works"; so no regression test can be done.
Acceptance criteria:
> Fix challenge repository crash when no available challenge

- lib/services/database/comment_upvote_repository_service.dart
- lib/services/database/post_upvote_repository_service.dart
- lib/services/database/upvote_repository_service.dart
This PR is a small refactor to make it easier to use post and comment upvote repositories.
It makes the constructor that uses database information private and exposes intuitive constructors for a post and comment upvote repo.
> upvote repositories refactor

- pubspec.yaml
- test/mocks/data/post_overview.dart
- test/mocks/overrides/override_human_time.dart
- test/mocks/providers/provider_human_time_service.dart
- test/mocks/providers/provider_post_page.dart
- test/services/human_time_service_test.dart
- test/views/pages/post/post_page_values_test.dart
Fixes #209
This PR's goal is to test two new parts of the application:
- The distances values between posts displayed as human readable format.
- The new human readable values provided by the new service added in PR #234.
The testing relies heavily on Dependency Injection to make sure relative times are consistent across different testing environments and time zones.
Don't hesitate to ask question below if anything in the code is not clear :)
**Note**: first relevant commit is 1a62d3f.
The testing is composed of two types of tests:
- Unit tests for the human time service that are done in `test/services/human_time_service_test.dart`
- Component testing for the human time service and the distances in the UI testing files.
I also added the providers override and helpers for testing the human …
> Test human readable time and distances values in UI

- lib/views/navigation/bottom_navigation_bar/navigation_bar_routes.dart
- lib/views/pages/home/content/ranking/ranking_card.dart
- lib/views/pages/home/content/ranking/ranking_list.dart
- lib/views/pages/home/content/ranking/ranking_widget.dart
- test/mocks/data/ranking_data.dart
- test/views/pages/home/content/ranking/static_ranking_list_test.dart
- test/views/pages/home/content/ranking/static_ranking_widget_test.dart
Fixes: #298 
This PR aims to provide the UI for the ranking page.
**Note:**  We are working with Lucas in parallel on the view and the view model. So we are trying to reduce the amount of conflicts on our tasks. In this PR, all the mock datas are in the view for the moment.
Acceptance Criteria:
> Ranking UI

- lib/viewmodels/challenge_view_model.dart
- lib/viewmodels/map/map_pin_view_model.dart
- test/views/pages/map/dynamic_map_test.dart
Fixes #296.
This PR adds the functionality of the "Challenges" selection chip above the map. Only uncompleted challenges are displayed on the map. Once a challenge is completed, the pins are refreshed. This is also completely tested.
This PR strongly depends on the code I added in #320. I already had this PR in mind, so I made some very modular code and tests immediately, hence this PR size. 
Happy PR reviewing :)
Acceptance criteria:
> Challenges option on the map

- lib/viewmodels/challenge_view_model.dart
- test/mocks/overrides/override_challenges_view_model.dart
- test/viewmodels/challenge_view_model_integration_test.dart
Fixes #267.
This PR changes the widget used for the challenges viewmodel to `AutoDisposeAsyncNotifier`, so that the challenges are refreshed on bottom bar navigation.
**Features:**
- `ChallengeViewModel` now extends `AutoDisposeAsyncNotifier<List<ChallengeDetails>>`
- Extended `challenge_viewmodel_integration_test` to check that the distance are correctly updated on user position change and viewmodel refresh
- Checking that the distance is correctly updated on user position change on bottom bar navigation will be handled by #220, as it requires a significant update of our end-to-end tests, with proper setup. (this was discussed with @Aderfish)
**Live testing:**
To test the feature, you can 
1. Navigate to the challenges page, check the distance
2. Move
3. Go to another page and come back …
> Refresh challenges

- lib/models/database/user_comment/user_comment_data.dart
- lib/services/database/comment/comment_repository_service.dart
- lib/viewmodels/user_comments_view_model.dart
- test/mocks/data/firestore_comment.dart
- test/mocks/data/user_comment_data.dart
- test/models/database/user_comment/user_comment_data_test.dart
- test/viewmodels/user_comment_view_model_test.dart
Hello,
This PR aims to sort the user comments on the profile page (issue #300).
Concretelly, this PR does the following:
**Add `publicationTime` field to `UserCommentData`:**
A new field `publicationTime` has been added to the `UserCommentData` to allow for the sorting.
Thus, the repository `CommentRepositoryService` as well as the tests and mocks for `UserCommentData` have been updated to take into account this new field.
**User comments view model:**
The view model to display the user comments will now sort the comments from latest to oldest before exposing them.
Thus, the latest comments of the user wil appear at the top of the list on the profile page.
**Tests:**
This PR provides a test for the ordering of the user comments exposed by the view model.
You can test this feature by doing …
> Sort user comments on profile page

- lib/services/database/upvote_repository_service.dart
- test/mocks/overrides/override_firebase_transaction.dart
- test/services/database/post_upvote_repository_test.dart
Fixes #160 
This PR aims to prevent the launch of an exception to the Flutter console when voting on a post without internet connectivity.
The bug is 100% reproducible, follow the steps below (on commit d1ae708):
- Open the app (in debug mode to have access to the flutter console)
- Login if not already logged in
- Load the posts on the feed or create one if there are no posts nearby
- Turn off the internet connection of the device
- Try to upvote the post on the feed
The following error is thrown on the Firebase console:
```txt
E/flutter (11839): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
E/flutter …
```
> Fix offline vote throws an exception

- test/mocks/data/firestore_post.dart
Fixes #344.
This PR makes the handling of the indices by `FirestorePostGenerator` consistent. Before, one function incremented it before using it, and the other incremented it after using it. This therefore created bugs that were very hard to notice, which depended on the order of execution of those two functions. 
Happy reviewing, this should be a PR fast to review! ;)
Acceptance criteria:
> Fix post generator id increment

- test/models/ui/validation/create_account_validation_test.dart
- test/models/ui/validation/new_comment_validation_test.dart
- test/models/ui/validation/new_post_validation_test.dart
This small PR tests hashcode and equality overrides that were not covered until now. 
Acceptance criteria:
> Test account and comment validation

- lib/models/ui/comment_details.dart
- lib/models/ui/linear_segmented_hsv_colormap.dart
- lib/models/ui/post_details.dart
- lib/viewmodels/map/map_view_model.dart
- lib/viewmodels/user_comments_view_model.dart
- lib/viewmodels/users_ranking_view_model.dart
- lib/views/components/async/loading_icon_button.dart
- lib/views/navigation/map_action.dart
- lib/views/pages/home/content/challenge/challenge_list.dart
- lib/views/pages/home/content/map/components/post_map.dart
- lib/views/pages/profile/profile_page.dart
A small PR just to apply all relevant DCM suggestions.
> Apply DCM main suggestions
